name: Audiobookshelf
version: "2.23.0"
slug: audiobookshelf
description: Self-hosted audiobook and podcast server
url: "https://github.com/advplyr/audiobookshelf"
image: "christopherjnash/audiobookshelf-ha-addon:2.23.0"

arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386

init: false
map:
  - media:ro
  - ssl:ro

ports:
  8083/tcp: 8083
ports_description:
  8083/tcp: Audiobookshelf Web Interface

environment:
  METADATA_PATH: /data/abs-metadata
  CONFIG_PATH: /data/abs-config
  PORT: "8083"
  HOST: "0.0.0.0"

webui: "http://[HOST]:[PORT:8083]"
