# config.yaml
name: Ghostboard
version: "1.0.0"
slug: ghostboard
description: Ghostboard real‑time text‑sharing add‑on for Home Assistant
url: "https://github.com/jon6fingrs/ghostboard"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options: {}
schema: {}
ports:
  80/tcp: 8765
webui: "http://[HOST]:[PORT:8765]"