name: Ghostboard
version: "1.0.0"
slug: ghostboard
description: Ghostboard add-on for Home Assistant
url: "https://github.com/jon6fingrs/ghostboard"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
init: false
ports:
  80/tcp: 8765
webui: "http://[HOST]:[PORT:8765]"