#!/usr/bin/with-contenv sh
APP_EXIT_CODE="$1"

if [ "$APP_EXIT_CODE" -ne 0 ] && [ "$APP_EXIT_CODE" -ne 256 ]; then
  echo "[WARNING] Halt add-on with exit code $APP_EXIT_CODE"
  echo "$APP_EXIT_CODE" > /run/s6-linux-init-container-results/exitcode
  exec /run/s6/basedir/bin/halt
fi

echo "[INFO] Service restart after closing"
