name: Readeck
version: "0.19.0"
slug: readeck
description: Readeck is a lightweight read-it-later app to save, organize, and export web content, ensuring privacy and user control over the reading list
url: "https://codeberg.org/readeck/readeck"

arch:
  - amd64
  - aarch64

init: false
map:
  - addon_config:rw

ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: Readeck Web Interface

environment:
  READECK_SERVER_HOST: 0.0.0.0
  READECK_SERVER_PORT: 8000

startup: services
webui: "http://[HOST]:[PORT:8000]"
