# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: RSS-Bridge
version: "1.1.0"
slug: rss-bridge
description: RSS-Bridge add-on for Home Assistant
url: "https://github.com/christopherjnash/home-assistant-addons/tree/main/rss-bridge"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  80/tcp: 8085
webui: "http://[HOST]:[PORT:8085]"