#!/command/with-contenv sh
# shellcheck shell=sh

set -e

# ==============================================================================
# S6-Overlay service run script for the Readeck Addon
# ==============================================================================

# Set default Readeck environment variables.
: "${READECK_SERVER_HOST:=0.0.0.0}"
: "${READECK_SERVER_PORT:=8001}"
: "${READECK_DATA_DIRECTORY:=/data}" # Explicitly set data directory to /data

export READECK_SERVER_HOST
export READECK_SERVER_PORT
export READECK_DATA_DIRECTORY # Export the data directory variable

# Start Readeck application.
echo "Starting Readeck server on ${READECK_SERVER_HOST}:${READECK_SERVER_PORT}..."
echo "Using data directory: ${READECK_DATA_DIRECTORY}"
exec exec /bin/readeck serve