# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Freetar
version: "0.14.0"
slug: freetar
description: Freetar add-on for Home Assistant
url: "https://github.com/kmille/freetar"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  username: "user"
  password: "pass"
schema:
  username: str
  password: str
ports:
  22001/tcp: 22001
ports_description:
  22001/tcp: Freetar Web Interface
webui: "http://[HOST]:[PORT:22001]"
